#!/bin/bash

#
# This scirpt helps library callers that is a Qt project
#
# Run this script in the library caller's source directory
# to generate a libsaki.pri corresponds to that PWD
#

LIB_ROOT=$(dirname $0)
qmake -project \
	-o libsaki.pri \
	-t lib \
	-nopwd \
	"INCLUDEPATH += $LIB_ROOT/3rd/lua" \
	$LIB_ROOT
sed -i '/TEMPLATE =/d' libsaki.pri
sed -i '/TARGET =/d' libsaki.pri
sed -i '/# Auto*/c\# Generated by libsaki/gen_pri.sh, do NOT modify' libsaki.pri

